### ISSUE TITLE
retrieving metadata with meta() and return array instead of data frame

### ISSUE THREAD

**Issue by annakat** [annakat/spectrolab#18]
You probably know better that I if returning an array when querying metadata would be generally advantageous. One case I just came across is this:

To get an overview of the metadata now associated with a spectra object, this works:
table(meta(spec_n, 5)<0, meta(spec_n) [,"sp"]) 

However, in analogy to: 
table(chem$nitrogen_perc<0, chem$sp) (...chem is the metadata table) 
I first tried to do: 
table(meta(spec_n, 5)<0, meta(spec_n, "sp")), which of course doesn't work.

**Comment by meireles** [comment]
I'm not sure what you mean. Can you place a reproducible example here?
Anyways, one can always:
1. summarize the returned object with `summary(meta(spec_n))`
2. assign metadata to a global variable `y = meta(spec_n)` and manipulate stuff there.

**Comment by annakat** [comment]
I'll email the file (spec_n) to you. 
meta(spec_n, "sp") returns a dataframe, which can be inconvenient in some cases (such as the above). meta(spec_n) [,"sp"]) returns a vector. 
Having meta(spec_n, "sp") returning a vector/matrix could be more convenient ... but I'm not sure.

**Comment by meireles** [comment]
No need to email the file.

I'm not sure if returning a matrix would always be more convenient because: 1) the user does not now if he'll get a data.frame or a matrix or a vector. 2) In many situations, returning a matrix is the wrong thing to do, because metadata can have many types, and a matrix by definition only holds elements of one type.

There is already a "simplify" argument, which returns a vector in case the user selected only one of the metadata elements (check that out).

Anyways, we may be able to extend this to the cases when returning a matrix is ok.

**Comment by annakat** [comment]
Ok, "simplify" does the trick. Great, thanks!
